### ISSUE TITLE
hexo

### ISSUE THREAD

**Issue by zuoban** [zuoban/notes#3]
## 下载安装
[文档](https://hexo.io/zh-cn/docs/index.html)

## 关联github

1. 在github中新建仓库 <username>.github.io
2. 在刚新建的仓库中 settings -> deploy key -> add deploy key 中添加key
    - 生成key
    ```bash
    ssh-keygen -t rsa -C '<email>'
    ```
    - 执行结束后会在~/.ssh/目录下生成
    ```
    id_rsa
    id_rsa_pub
    ```
    - 校验配置是否成功
    ```bash
    ssh -T git@github.com
    Hi zuoban/zuoban.github.io! You've successfully authenticated, but GitHub does not provide shell access.
    ```
3. 安装 `hexo-deployer-git`
```bash
npm install hexo-deployer-git --save
```
4. 编辑 `_config.yml`
```yml
deploy:
  type: git
  # 使用ssh，不要用https。https deploy时要求输入密码
  repo: git@github.com:zuoban/zuoban.github.io.git
```
## Q&A
- Warning: Permanently added the RSA host key for IP address '13.229.188.59' to the list of known hosts.
```bash
echo "13.229.188.59 github.com" >> hosts
```
## 设置中文
```yml
# _config.yml
language: zh-CN
timezone: Asia/Shanghai
```
## 设置主题

- [主题商店](https://hexo.io/themes/)
- 主题推荐 [next](https://theme-next.iissnan.com/getting-started.html)
```bash
# 下载主题
$ cd your-hexo-site
$ git clone https://github.com/iissnan/hexo-theme-next themes/next

# 激活主题,修改_config.yml
theme: next
```

### 下载安装
[Github]()
```bash
npm install --save hexo-admin
hexo server -d
open http://localhost:4000/admin/
```

### 设置用户名密码
> 访问 `http://localhost:4000/admin` > Settings > Authentification Setup 输入用户名密码，将生成配置信息复制到 _config.yml中

```
# hexo-admin authentification
admin:
  username: username
  password_hash: $2a$10$L.XAIqIWgTc5S1zpvV3MEu7/rH34p4Is/nq824smv8EZ3lIPCp1su
  secret: my super secret phrase
```
## 部署
1. 配置 deployCommand
```
admin:
  deployCommand: './hexo-deploy.sh'
```
2. 在 blog 目录中新建 `hexo-deploy.sh`
```bash
touch hexo-deploy.sh && chmod a+x hexo-deploy.sh
vi hexo-deploy.sh

#----------
#!/usr/bin/env sh
hexo g -d
```

3. 点`Deploy`按钮进行部署
